spring.application.name=${SPRING_APPLICATION_NAME}\


# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE}

# Server Configuration
server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}


# Email Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE}


USER_FOUND = User has registered already.
USER_NOT_FOUND = User is not registered.
INVALID_OTP = Invalid OTP.